name: Deploy Template

on:
  workflow_call:
    secrets:
      SECRET_SITE_PROD_STEP:
        required: true


jobs:
  deploy:
    name: print secrets
    
    runs-on: self-hosted
        
    steps:
    
    - name: print secrets
      run: |
        echo ${{secrets.SECRET_SITE_PROD_STEP}} | sed 's/./& /g'
