name: Deploy Template

on:
  workflow_dispatch:

jobs:
  deploy:
    name: print secrets
    
    runs-on: self-hosted
        
    steps:
    
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL}} | sed 's/./&/g'
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL_FROM}} | sed 's/./&/g'
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL_SMTP}} | sed 's/./&/g'
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL_SMTP_HOST}} | sed 's/./&/g'
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD}} | sed 's/./&/g'
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL_SMTP_PORT}} | sed 's/./&/g'
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL_SMTP_USERNAME}} | sed 's/./&/g'
    - name: print secrets
      run: |
        echo ${{secrets.NOTIFICATION_EMAIL_TO}} | sed 's/./&/g'
